// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjjczlhybgeslfiovkun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqamN6bGh5Ymdlc2xmaW92a3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjUyODMsImV4cCI6MjA3MTk0MTI4M30.aqB0dFiAlwhomMITSeSLld9S7LeOh2oEf7kWnI47T4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});